### ISSUE TITLE
可以提供一下这些静态库吗？

### ISSUE THREAD

**Issue by HuangHongkai** [fanxiushu/stream_push#1]
里面的libx264.a libavutil.a libavcodec.a 等等这些静态库可以发给我一下吗？

**Comment by fanxiushu** [comment]
> 
> 
> 里面的libx264.a libavutil.a libavcodec.a 等等这些静态库可以发给我一下吗？我的邮箱：[2523272490@qq.com](mailto:2523272490@qq.com)

这个你自己尝试着编译啊，不大可能什么都提供，再说也没必要。
就当熟悉一下ffmpeg编译环境，相信自己，熟悉了之后其实也就是几个参数选择的问题。祝好。
