### ISSUE TITLE
该工程目前支持推流到哪几个平台？

### ISSUE THREAD

**Issue by llatecomers** [fanxiushu/stream_push#4]
你好，请问该项目有测试过rtmp推流到srs和阿里云上面嘛？
以及桌面录制的延迟和拉流播放的延迟大概在什么范围？

**Comment by fanxiushu** [comment]
支持RTMP协议或RTSP协议推流的服务器都能支持，
至于你说的srs和阿里云，你可以自己去测试。
这个工程的核心是ffmpeg开源工程。你如果直接使用ffmpeg程序能推流到你所说的平台，
该工程也会同样支持。
至于延迟什么的，推送部分与ffmpeg一致，拉流取决于服务器端的性能。

**Comment by llatecomers** [comment]
我这边测试了推流到腾讯云ok，srs目前没有环境验证，功能ok，感谢up大大。
